### ISSUE TITLE
Open dialog not fully visible on iPhone

### ISSUE THREAD

**Issue by narcistesa** [diesys/transmission-web-soft-theme#3]
This looks like a bug, the open dialog snaps to the left of the screen on an iPhone and it isn't fully visible. Thanks.

**Comment by diesys** [comment]
Sorry i don't have any iPhones to test the theme with them.. but there is a main problem even before starting to debug it, this is just a CSS theme, many problems are caused by the really html-unfriendly generated by transmission itself for the web interface. I tried to fix many problems but usually the fixes start to make other things go wrong because of the bad HTML it's styling.
The web interface of Transmission itself should be updated to have a way cleaner and simpler to maintain UI and CSS theming.

I don't know how and if I can fix this bug and if it's a CSS or HTML bug. Without the theme does it work?

**Comment by narcistesa** [comment]
Yes, the open dialog is centered fine and usable without the theme, it's possible that the theme dialog animation gets confused on a smaller screen. I would assume it would have the same issue on any small screen or smartphone (`max-device-width: 480px` from _index.html_). I agree that the Transmission web ui needs an update, it looks very outdated.
